### ISSUE TITLE
single entry point for webapps.

### ISSUE THREAD

**Issue by hushicai** [fgnass/gateway#3]
Hi, i wonder whehter if this gateway could serve a single entry point?If a request uri is not a real path on server,should it rewrite to the 'index.php'?That means we should check the existment of 'docroot + url.pathname' in the function 'resolveIndexFiles',it may be a file or a directory,if do not exist,rewrite to the 'index.php'.

**Comment by brodkin** [comment]
I have the same problem. Magento has an index.php file that acts as a front controller for everything. I either need to be able to route to `localhost:9000/index.php/category` or `localhost:9000/category` with index.php being accessed in the backend. I'm not sure if this needs to be handled by the middleware or by node.

**Comment by ctrix** [comment]
@hushicai @brodkin I had the same identical problem and i wrote another version which you can find in my github repositories 

https://github.com/ctrix/gateway-rewrite

Hope it helps.
